training_settings:
  models:
    # - "Logistic Regression"
    # - "Decision Tree"
    - "Random Forest"
    # - "Gradient Boosting"
    # - "SVM"
    - "KNN"
    - "XGBoost"
    - "Naive Bayes"
    # - "MLP"
    - "LSTM"

  selectors:
    - "none"
    # - "pca"
    # # - "rfe"
    # - "rf"
    # - "mi"
