training:
  models:
    active:
      - Naive Bayes
      # - Logistic Regression
      # - Decision Tree
      # - Random Forest
      # - Gradient Boosting
      # - KNN
      # - XGBoost
      # - MLP
  feature_selection:
    active:
      - none
      - pca
      # - rfe
      # - rf
      # - mi
