models_config:
  available_models:
    - Logistic Regression
    - Decision Tree
    - Random Forest
    - Gradient Boosting
    - KNN
    - XGBoost
    - Naive Bayes
    - MLP
  
  default_parameters:
    Logistic Regression:
      max_iter: 5000
      class_weight: balanced
    Random Forest:
      n_estimators: 100
      class_weight: balanced